### PR TITLE
CouchPotato, MariaDB, Pydio, ruTorrentVPN, SickRage, SickChill - V8.5

### PR DESCRIPTION
**Pull request by ChaosZero112**
Adds:

- CouchPotato
- MariaDB
- Pydio
- ruTorrentVPN
- SickRage
- SickChill

If someone could take a look at the mounts, I wasn't sure of the proper places for some (couchpotato, pydio, sickrage and sickchill)

### CODE REVIEW

**Comment by robertbaker** [comment]
I would remove the custom /downloads, /tv, and /movies volume mounts.
While they would work, they are not needed and have downsides.

**Comment by ChaosZero112** [comment]
> I would remove the custom /downloads, /tv, and /movies volume mounts.
> While they would work, they are not needed and have downsides.

Removing the mounts, without modifying the Dockerfile, would cause the creation of docker volumes. That's the intended scenario?

**Comment by robertbaker** [comment]
Those we cleanup automatically.

The problem is people will use /movies, then when connecting apps together
things don't work and then it's a needle in a haystack to figure out it's
because they are using the "wrong" path.

Even though it's valid in docker, those mappings won't work for other apps
because they don't exist.

Forcing people to use the "real" path takes care of many of those issues,
because /mnt/unionfs exists on the server and it's the same inside docker,
so there isn't any "path translation" needed.

Additionally every volume mappings is a separate docker volume.

If someone was using /downloads and /movies, hardlinking won't work in that
case, then we get support "bugs".

**Comment by ChaosZero112** [comment]
Removed the mounts.

Flood and Flexget also were added as part of the merge.

**Comment by robertbaker** [comment]
Is your intention to support these apps? We don't really want to add apps for the sake of adding them. Some users will install and if it doesn't work (or act how they want), there will be support requests.

Why are you adding sick chill and sickrage, Medusa, couch potato? Is there a huge demand for old obsolete apps to longer under development?

These are alternatives to the core apps, I understand but there was a reason we dropped them. We don't know them, nor do we want to support them.

Once they are in community, it's up to the community to support them, but honestly I found that it ends up being us to fix other people's containers.

Additionally, do those PVRs hardlink? Have you tested if it copies or hardlinks. We already deal with support requests about hardlinking, so if hardlinks don't work, it's not a good idea to merge that in.

IMO there's not enough justification to merge these barely used (at this point) apps, they will just increase support forums and discord requests. Additionally there's no wiki pages for configuration with screenshots and stuff like we have. We would definitely need that for them if we did merge them in.

**Comment by ChaosZero112** [comment]
Most apps added are in active development.
Pydio - [GitHub](https://github.com/linuxserver/docker-pydio)
SickChill - [GitHub](https://github.com/SickChill/SickChill)
SickRage - [Git](https://git.sickrage.ca/SiCKRAGE/sickrage)
ruTorrentVPN - [GitHub](https://github.com/binhex/arch-rtorrentvpn)
CouchPotato is still being patched - [GitHub](https://github.com/CouchPotato/CouchPotatoServer/)

I didn't add Medusa, just repaired it. But I have noticed Medusa works better for Anime than Sonarr.

I have no issue supporting the deployment of the apps, the usage would be a bit more tricky.

I added SickChill, SickRage and CouchPotato as available options, but I won't be actively using them myself. Sonarr 3

I can scrap those 3, and leave the additions of Flood, FlexGet, Pydio, MariaDB, ruTorrentVPN, PlexRequests. Those I will be using actively and can support better.

**Comment by Admin9705** [comment]
this is a good push, but it's too much. :D if you made one per app and started so we can test :D but i can look at this as a reference also.

**Comment by ChaosZero112** [comment]
Broke down the apps. I'll re-submit the pull as individual requests.

**Pull request closed without merging**
