### PR TITLE
Update organizr.yml

### PR DESCRIPTION
**Pull request by Artiume**
Updated to be HSTS compliant

### CODE REVIEW

**Comment by robertbaker** [comment]
This is not the place to do this, in most of the options you are setting are just the defaults and redundant.

The proper place would be here: https://github.com/PGBlitz/Traefik/blob/v8.6/templates/traefik.toml

**Comment by Artiume** [comment]
Robert,

Some apps do not support all of the security features introduced with HSTS. It needs to be on app per app basis. Also, do you have documentation to show that these are implemented by default? I've done plenty of builds and I definitely see the difference.

**Comment by robertbaker** [comment]
@Artiume It appears in the upcoming traefik v2, they removed the ability to do these globally.
Since you deleted the branches or fork, it won't let me re-open.

If you wouldn't mind, please add these labels to all the core apps (then test) and submit a PR.

**Comment by Artiume** [comment]
Yeah, I'm still getting used to Git. Once I figure out how to resolve the fork conflict I keep getting, I'll resubmit the pull request.

**Pull request closed without merging**
